credentials:
  usernames:
    sbs.anna.ciboro@gmail.com:
      email: sbs.anna.ciboro@gmail.com
      name: Anna Ciboro
      password: "$2b$12$/e117bp3xq3bi80h/4Y4w.X.pCmfBOaVMeQpxmonw08GaMF4yOwp6"  # met1
      admin: true

cookie:
  expiry_days: 0
  key: "7eb707cb9ec9120e9f9ef0edb40dbb3b"
  name: "sbs_auth"

preauthorized:
  emails:
    - sbs.anna.ciboro@gmail.com